### ISSUE TITLE
Unable to save KTXBZ as PNG with v0.1.0

### ISSUE THREAD

**Issue by legendofmi** [Didero/ThimbleMonkey#4]
I am unable to save KTXBZ files into PNGs. This is a regression as it was working with previous versions.
`qt.qpa.window: Window position QRect(-240,-218 1920x1280) outside any known screen, using primary screen
2022-12-29 22:33:39.497 Python[10362:301476] +[CATransaction synchronize] called within transaction
2022-12-29 22:34:05.534 Python[10362:301476] +[CATransaction synchronize] called within transaction
Traceback (most recent call last):
  File "/Users/user/Downloads/ThimbleMonkey-main/ui/MainWindow.py", line 78, in <lambda>
    WidgetHelpers.createMenuAction(fileMenu, "&Convert and save current tab data", lambda: self.saveTabData(True), "Convert and save the tab data as something usable")
  File "/Users/user/Downloads/ThimbleMonkey-main/ui/MainWindow.py", line 206, in saveTabData
    raise ValueError(f"Unsupported file data format '{type(fileData).__name__}'")
ValueError: Unsupported file data format 'Image'`

**Comment by Didero** [comment]
Oh, thanks for the report! I was so focussed on getting the soundbanks to work that I didn't fully test existing functionality that I assumed would keep working.
This is fixed in commit https://github.com/Didero/ThimbleMonkey/commit/968be830d43a549d17455b108d1da53c6a26248c
I'll make a new release if and when I make any headway with #3 unless that takes too long.
Thanks again!
